name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./app --tag shikhov/tg-facecontrol
    - name: Docker login
      run: docker login -u shikhov -p ${{secrets.DOCKER_HUB_TOKEN}}
    - name: Push to Docker Hub
      run: docker push shikhov/tg-facecontrol:latest
