name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # - name: Build the Docker image
    #   run: docker build ./app --tag shikhov/tg-facecontrol
    # - name: Docker login
    #   run: docker login -u shikhov -p ${{secrets.DOCKER_HUB_TOKEN}}
    # - name: Push to Docker Hub
    #   run: docker push shikhov/tg-facecontrol:latest


    # - name: Set up Docker
    #   uses: docker/setup-docker-action@v4
    #   with:
    #     daemon-config: |
    #       {
    #         "debug": true,
    #         "features": {
    #           "containerd-snapshotter": true
    #         }
    #       }

   

    - name: Docker login
      run: docker login -u shikhov -p ${{secrets.DOCKER_HUB_TOKEN}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        context: ./app/
        load: true
        tags: shikhov/tg-facecontrol:latest
